name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "17 16 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Generate GitHub profile summary cards
    runs-on: ubuntu-latest

    steps:
      - name: Checkout profile repo
        uses: actions/checkout@v4

      - name: Generate summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: main
          UTC_OFFSET: 8
          EXCLUDE: ""
          AUTO_PUSH: true
